# Erstelle Liste von Kreisen und Orten

Als Input dient [diese Seite](https://www.woerterbuchnetz.de/Woerterbuecher/WWB/KreiseOrte.html), die eine Liste aller Landschafts-, Kreis-, und Ortskürzel enthält. Sie ist mit HTML formatiert und dadurch sollten sich die Orte relativ einfach herausfiltern lassen.

In [17]:
import pandas as pd
import regex as re

In [18]:
# Open the raw HTML file
with open('../data/raw/KreiseOrte.html', 'r', encoding='latin-1') as f:
    html = f.read()

# Replace a few characters
html = re.sub(r'&#8594;', '→', html)
html = re.sub(r'\*', '', html)
html = re.sub(r'Ö¶', 'ö', html)
html = re.sub(r'Ö¼', 'ü', html)
html = re.sub(r'Ã¤', 'ä', html)
html = re.sub(r'Ã¶', 'ö', html)
html = re.sub(r'Ã¼', 'ü', html)
html = re.sub(r'Ã', 'Ö', html)
html = re.sub(r'Ã', 'Ü', html)

# First group ^= Landschaften, second group ^= Kreise und Orte
html = re.findall(r'<dl class="preface-definitionlist">(.+?)</dl>', html, flags=re.DOTALL)[1]

# Split up lines
html_lines = html.split('\n')

In [19]:
# Lists for holding the data that will later make up the dataframes
kreis_shorts = []
kreis_longs = []

ort_kreis = []
ort_shorts = []
ort_longs = []

for line in html_lines:
    # If the line contains a Kreis, remember all information about it
    new_kreis = re.findall(r'<dt class="preface-definitionterm-header">(.+?)</dt><dd class="preface-definition-header">(.+?)</dd>', line)
    if len(new_kreis):
        kreis_short = new_kreis[0][0]
        kreis_long = new_kreis[0][1]

        kreis_shorts.append(kreis_short)
        kreis_longs.append(kreis_long)

    # If the line contains an Ort, remember all information about it
    new_ort = re.findall(r'<dt class="preface-definitionterm"><a class="wwb-location-search-link" href="javascript:searchLocation\(\'WWB\',\'(?:.+?)\'\);">(.+?)</a></dt><dd class="preface-definition">(.+?)</dd>', line)
    if len(new_ort):
        ort_short = new_ort[0][0]
        ort_long = new_ort[0][1]

        ort_kreis.append(kreis_short)
        ort_shorts.append(ort_short)
        ort_longs.append(ort_long)

# Combine the lists created above into dataframes
kreis_df = pd.DataFrame({'Abkuerzung': kreis_shorts, 'Name': kreis_longs})
orte_df = pd.DataFrame({'Kreis': ort_kreis, 'Abkuerzung': ort_shorts, 'Name': ort_longs})

# Save the dataframes as CSVs
#kreis_df.to_csv('../data/processed/Kreise.csv', index=False, sep='\t')
#orte_df.to_csv('../data/processed/Orte.csv', index=False, sep='\t')

## Achtung! Nachdem die Liste der Orte automatisch erstellt wurde, müssen die großen Ö’s und Ü’s händisch eingefügt werden!

### Ergebnisse:

In [20]:
# Manuell geschriebene Tabelle
landschaften = pd.read_csv('../data/processed/Landschaften.csv', delimiter='\t')
landschaften

,Abkuerzung,Name,Beschreibung
0,Emsl,Emsland,"Emsland d. h. die Kreise Lingen, Meppen, Asche..."
1,HOsnabr,Hochstift Ösnabrück,"das frühere Hochstift Osnabrück, vornehmlich d..."
2,HPaderb,Hochstift Paderborn,"das frühere Hochstift Paderborn, d. h. die Kre..."
3,KSauerl,Kölnisches Sauerland,"Kölnisches Sauerland, d. h. die Kreise Arnsber..."
4,Lip,Lippe,"das frühere Land Lippe, d. h. die Kreise Detmo..."
5,Mark,Grafschaft Mark,die frühere Grafschaft Mark
6,Münsterl,Münsterland,Münsterland
7,Ravensbg,Grafschaft Ravensberg,die frühere Grafschaft Ravensberg
8,SOldbg,Südoldenburg,"Südoldenburg, d. h. die Kreise Vechta und Clop..."
9,WMünsterl,Westmünsterland,Westmünsterland

In [21]:
kreise = pd.read_csv('../data/processed/Kreise.csv', delimiter='\t')
kreise

   Abkuerzung                                               Name
0         Ahs                                          Kr. Ahaus
1         Alt          Kr. Altena u. die krfr. Stadt Lüdenscheid
2         Arn                                       Kr. Arnsberg
3         Asd                            Kr. Aschendorf-Hümmling
4         Bbr                                    Kr. Bersenbrück
5         Bch     die krfr. Städte Bochum, Herne u. Wattenscheid
6         Bek                                         Kr. Beckum
7         Ben                            Kr. Grafschaft Bentheim
8         Bie                                      Kr. Bielefeld
9         Bor              Kr. Borken u. die krfr. Stadt Bocholt
10        Brg  an Westfalen grenzende Teile der krfr. Stadt W...
11        Bri                                         Kr. Brilon
12        Bük               früherer Verwaltungsbezirk Bückeburg
13        Bür                                          Kr. Büren
14        Det                                        Kr. Detmold
15        Die                            Kr. Grafschaft Diepholz
16        Dor  die krfr. Städte Dortmund, Castrop-Rauxel u. L...
17        Enr                                  Ennepe-Ruhr-Kreis
18        Ess               die krfr. Städte Essen u. Oberhausen
19        Gel     die krfr. Städte Gelsenkirchen u. Wanne-Eickel
20        Hag                              die krfr. Stadt Hagen
21        Hal                                          Kr. Halle
22        Ham                                        Ha → Unn Hx
23        Hfd                                        Kr. Herford
24        Höx                                         Kr. Höxter
25        Isl                                       Kr. Iserlohn
26        Klo                                    Kr. Cloppenburg
27        Kos                                       Kr. Coesfeld
28        Lem                                          Kr. Lemgo
29        Lhs                                   Kr. Lüdinghausen
30        Lin                                         Kr. Lingen
31        Lst                                      Kr. Lippstadt
32        Lüb                                       Kr. Lübbecke
33        Mel                                          Kr. Melle
34        Mep                                         Kr. Meppen
35        Mes                                       Kr. Meschede
36        Min                                         Kr. Minden
37        Mün                                        Kr. Münster
38        Nie                               Kr. Nienburg (Weser)
39        Olp                                           Kr. Olpe
40        Osn                                      Kr. Osnabrück
41        Pad                                      Kr. Paderborn
42        Rek  Kr. Recklinghausen u. die krfr. Städte Bottrop...
43        Sch                          Kr. Grafschaft Schaumburg
44        Sos                                          Kr. Soest
45        Stf                                      Kr. Steinfurt
46        Sth              früherer Verwaltungsbezirk Stadthagen
47        Tek                                    Kr. Tecklenburg
48        Unn                   Kr. Unna u. die krfr. Stadt Hamm
49        Vch                                         Kr. Vechta
50        Wal  Kr. Waldeck u. Kr. Frankenberg (niederdeutsche...
51        Wbg                                        Kr. Warburg
52        Wdf                                      Kr. Warendorf
53        Wie                                    Kr. Wiedenbrück
54        Wit                             die krfr. Stadt Witten
55        Wlg                                       Kr. Wittlage
56        Wol               Kr. Wolfhagen (niederdeutscher Teil)
57        Wtg            Kr. Wittgenstein (niederdeutscher Teil)

In [22]:
orte = pd.read_csv('../data/processed/Orte.csv', delimiter='\t')
orte

     Kreis Abkuerzung             Name
0      Ahs         Ab           Asbeck
1      Ahs         Ae      Ahle (Heek)
2      Ahs         Ah            Ahaus
3      Ahs         Al         Alstätte
4      Ahs         Am           Ammeln
...    ...        ...              ...
2727   Wol         We      Wettesingen
2728   Wol         Wh  Wenigenhasungen
2729   Wol         Wo        Wolfhagen
2730   Wtg         Lw       Langewiese
2731   Wtg         Na     Neuastenberg

[2732 rows x 3 columns]